description = "Generates a set of 10 technical flashcards in a specific CSV/HTML format for Anki."

prompt = """
Act as an expert computer science educator and content creator for the Anki flashcard platform. Your task is to generate a set of exactly 10 technical flashcards on a topic provided by the user. You must adhere strictly to all formatting and content requirements.

**User's Topic:** "{{args}}"

**FORMAT REQUIREMENTS:**
1.  **CSV Output:** The final output must be in CSV format, using a TAB character as the separator.
2.  **Single Line:** Each flashcard (all 4 columns) must be on a single line. Use `<br>` for line breaks within a field. Do not use actual newlines.
3.  **Four Columns:**
    - Column 1: "Difficulty" (e.g., "Beginner", "Intermediate", "Advanced", "Expert")
    - Column 2: "Topic::Subtopic-Number" (e.g., "Pointers::001-Declaration")
    - Column 3: "Question"
    - Column 4: "Answer"
4.  **Field Enclosure:** Every field must be enclosed in double quotes (`"`).
5.  **Code Formatting:** All C code examples must be wrapped in `<pre style="display:flex; justify-content:center;"><code class="language-c">...</code></pre>`.

**CONTENT GUIDELINES:**
1.  **Progression:** The 10 flashcards should progress in difficulty from fundamental concepts to advanced edge cases.
2.  **Question Structure:**
    - Start with a unique numbered identifier (e.g., "001/").
    - Include a relevant emoji.
    - Present a clear technical problem, often with a code example.
    - Provide four plausible multiple-choice options (A, B, C, D).
3.  **Answer Structure:**
    - Start with `<br><b>Answer</b>: [Correct Letter]`.
    - Provide a `<br><br><b>Explanation</b>:` section that is detailed and technical.
    - Explain not only why the correct answer is right, but also why the other options are incorrect.
    - Include a 🧠 **Mnemonic** where possible to aid memory.
    - Focus on common pitfalls, edge cases, and real-world implications (e.g., memory management, performance).

Generate the 10 flashcards for the user's topic now, following all rules precisely.
"""
