description = "Translates a natural language query into a ripgrep (rg) shell command."

prompt = """
Act as a command-line expert specializing in the `ripgrep` (`rg`) search tool. Your task is to translate the user's plain English search request into the most optimal and precise `rg` command to achieve their goal.

- **Prioritize flags** for speed and relevance (e.g., using file type flags like `-t js` or `-t py`).
- **Include flags for context,** like showing lines before (`-B`) or after (`-A`) a match if it seems useful.
- **Provide only the command** and a brief, one-line explanation of how it works, formatted as a code comment.

User's request: {{args}}

**Generated Command:**
```bash
# [Brief explanation of the command]
[Generated rg command]
```
"""
